/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          50:  '#eef2ff',
          100: '#e0e7ff',
          200: '#c7d2fe',
          300: '#a5b4fc',
          400: '#818cf8',
          500: '#6366f1',
          600: '#4f46e5',
          700: '#4338ca',
          800: '#3730a3',
          900: '#312e81',
        },
        surface: {
          0:  '#0a0b0f',
          1:  '#0f1017',
          2:  '#13141e',
          3:  '#1a1b26',
          4:  '#1e2035',
          5:  '#252640',
          border: '#2a2b3d',
          hover: '#2e2f4a',
        },
        agent: {
          chat:      '#22d3ee',
          planner:   '#a78bfa',
          coding:    '#34d399',
          debug:     '#f87171',
          memory:    '#fbbf24',
          connector: '#60a5fa',
          deploy:    '#f472b6',
          workflow:  '#fb923c',
          sandbox:   '#4ade80',
          ui:        '#e879f9',
        },
        neon: {
          green:  '#00ff88',
          blue:   '#00d4ff',
          purple: '#bf00ff',
          pink:   '#ff0080',
        },
      },
      fontFamily: {
        mono: ['JetBrains Mono', 'Fira Code', 'Cascadia Code', 'monospace'],
        sans: ['Inter', 'system-ui', 'sans-serif'],
        burmese: ['Pyidaungsu', 'Myanmar Text', 'sans-serif'],
      },
      animation: {
        'typing':        'typing 1.2s steps(3) infinite',
        'pulse-slow':    'pulse 3s ease-in-out infinite',
        'fade-in':       'fadeIn 0.3s ease-out',
        'slide-up':      'slideUp 0.3s ease-out',
        'slide-right':   'slideRight 0.25s ease-out',
        'glow':          'glow 2s ease-in-out infinite',
        'shimmer':       'shimmer 2s linear infinite',
        'spin-slow':     'spin 3s linear infinite',
        'bounce-dot':    'bounceDot 1.4s ease-in-out infinite',
      },
      keyframes: {
        typing:     { '0%,100%': { opacity: '0.2' }, '50%': { opacity: '1' } },
        fadeIn:     { from: { opacity: '0', transform: 'translateY(4px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        slideUp:    { from: { opacity: '0', transform: 'translateY(12px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        slideRight: { from: { opacity: '0', transform: 'translateX(-12px)' }, to: { opacity: '1', transform: 'translateX(0)' } },
        glow:       { '0%,100%': { boxShadow: '0 0 8px rgba(99,102,241,0.4)' }, '50%': { boxShadow: '0 0 20px rgba(99,102,241,0.8)' } },
        shimmer:    { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
        bounceDot:  { '0%,80%,100%': { transform: 'scale(0)' }, '40%': { transform: 'scale(1)' } },
      },
      backgroundImage: {
        'gradient-radial':  'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic':   'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
        'god-gradient':     'linear-gradient(135deg, #6366f1 0%, #8b5cf6 50%, #a78bfa 100%)',
        'neon-gradient':    'linear-gradient(90deg, #00ff88, #00d4ff, #bf00ff)',
        'glass-gradient':   'linear-gradient(135deg, rgba(255,255,255,0.05) 0%, rgba(255,255,255,0.02) 100%)',
      },
      backdropBlur: {
        xs: '2px',
      },
    },
  },
  plugins: [],
}
