export type WorkerRole = 'cognition' | 'automation' | 'execution' | 'repair' | 'visual_intelligence'

export interface WorkerSpaceSpec {
  id: string
  name: string
  shortName: string
  icon: string
  color: string
  layer: string
  description: string
  responsibilities: string[]
  roles: WorkerRole[]
}

export const SPACE_CATALOG: WorkerSpaceSpec[] = [
  { id: 'god-core-space', name: 'God Core Space', shortName: 'Core', icon: '🧠', color: '#7c3aed', layer: 'Core Cognitive Layer', description: 'System brain for orchestration, planning, reasoning, workflow control, mission state, websocket events, and model routing.', responsibilities: ['orchestrator', 'planner', 'reasoning', 'task graph', 'workflow engine', 'mission state', 'memory routing', 'websocket events', 'LLM routing'], roles: ['cognition', 'automation'] },
  { id: 'coding-worker-space', name: 'Coding Worker Space', shortName: 'Coding', icon: '🔧', color: '#f59e0b', layer: 'Execution Layer', description: 'Code generation, file editing, refactoring, dependency handling, and code transformations.', responsibilities: ['code generation', 'file editing', 'refactoring', 'dependency handling', 'code transformations'], roles: ['execution', 'cognition', 'automation'] },
  { id: 'sandbox-worker-space', name: 'Sandbox Worker Space', shortName: 'Sandbox', icon: '🧪', color: '#10b981', layer: 'Execution Layer', description: 'Isolated execution, runtime sandboxing, subprocesses, environment resets, and lifecycle management.', responsibilities: ['isolated execution', 'docker runtime', 'subprocesses', 'environment resets', 'runtime lifecycle'], roles: ['execution', 'repair'] },
  { id: 'terminal-worker-space', name: 'Terminal Worker Space', shortName: 'Terminal', icon: '⌨️', color: '#14b8a6', layer: 'Execution Layer', description: 'Shell commands, package installs, build tools, and process monitoring.', responsibilities: ['shell commands', 'package installs', 'build tools', 'process monitoring'], roles: ['execution', 'automation'] },
  { id: 'filesystem-worker-space', name: 'Filesystem Worker Space', shortName: 'FS', icon: '🗂️', color: '#22c55e', layer: 'Execution Layer', description: 'File writes, project trees, artifact management, and storage operations.', responsibilities: ['file writes', 'project trees', 'artifact management', 'storage operations'], roles: ['execution', 'automation'] },
  { id: 'browser-worker-space', name: 'Browser Worker Space', shortName: 'Browser', icon: '🌐', color: '#3b82f6', layer: 'Browser + UI Intelligence', description: 'Playwright automation, navigation, screenshots, and interaction testing.', responsibilities: ['playwright', 'browser automation', 'navigation', 'screenshots', 'interaction testing'], roles: ['automation', 'cognition'] },
  { id: 'vision-worker-space', name: 'Vision Worker Space', shortName: 'Vision', icon: '👁️', color: '#ec4899', layer: 'Browser + UI Intelligence', description: 'Screenshot analysis, OCR, layout detection, visual regression, and UI understanding.', responsibilities: ['screenshot analysis', 'OCR', 'layout detection', 'visual regression', 'UI understanding'], roles: ['visual_intelligence', 'cognition'] },
  { id: 'ui-worker-space', name: 'UI Worker Space', shortName: 'UI', icon: '🎨', color: '#8b5cf6', layer: 'Browser + UI Intelligence', description: 'Frontend generation, design systems, responsive layouts, component consistency, and visual polish.', responsibilities: ['frontend generation', 'design systems', 'responsive layouts', 'component consistency', 'visual polish'], roles: ['visual_intelligence', 'execution'] },
  { id: 'debug-worker-space', name: 'Debug Worker Space', shortName: 'Debug', icon: '🐛', color: '#ef4444', layer: 'Verification + Repair Layer', description: 'Error analysis, traceback parsing, repair strategies, and retry planning.', responsibilities: ['error analysis', 'traceback parsing', 'repair strategies', 'retry planning'], roles: ['repair', 'cognition'] },
  { id: 'test-worker-space', name: 'Test Worker Space', shortName: 'Test', icon: '🧪', color: '#06b6d4', layer: 'Verification + Repair Layer', description: 'Run tests, assertions, integration checks, and regression testing.', responsibilities: ['run tests', 'assertions', 'integration checks', 'regression testing'], roles: ['execution', 'repair'] },
  { id: 'verification-worker-space', name: 'Verification Worker Space', shortName: 'Verify', icon: '✅', color: '#84cc16', layer: 'Verification + Repair Layer', description: 'Validate outputs, compare expectations, quality scoring, and mission verification.', responsibilities: ['validate outputs', 'compare expectations', 'quality scoring', 'mission verification'], roles: ['repair', 'cognition'] },
  { id: 'git-worker-space', name: 'Git Worker Space', shortName: 'Git', icon: '🌳', color: '#f97316', layer: 'Deployment Layer', description: 'Commits, branching, diffs, merges, and repository workflow operations.', responsibilities: ['commits', 'branching', 'diffs', 'merges'], roles: ['automation', 'execution'] },
  { id: 'deploy-worker-space', name: 'Deploy Worker Space', shortName: 'Deploy', icon: '🚀', color: '#0ea5e9', layer: 'Deployment Layer', description: 'Vercel, Railway, Docker deploys, preview URLs, and CI/CD triggers.', responsibilities: ['Vercel deploy', 'Railway deploy', 'Docker deploy', 'preview URLs', 'CI/CD triggers'], roles: ['automation', 'execution'] },
  { id: 'connector-worker-space', name: 'Connector Worker Space', shortName: 'Connector', icon: '🔌', color: '#6366f1', layer: 'Deployment Layer', description: 'GitHub, Supabase, APIs, and external integrations.', responsibilities: ['GitHub', 'Supabase', 'APIs', 'external integrations'], roles: ['automation', 'cognition'] },
  { id: 'memory-worker-space', name: 'Memory Worker Space', shortName: 'Memory', icon: '🧠', color: '#a855f7', layer: 'Memory + Knowledge Layer', description: 'Vector DB, execution history, learned fixes, project memory, and long-term state.', responsibilities: ['vector DB', 'execution history', 'learned fixes', 'project memory', 'long-term state'], roles: ['cognition', 'automation'] },
  { id: 'knowledge-worker-space', name: 'Knowledge Worker Space', shortName: 'Knowledge', icon: '📚', color: '#4f46e5', layer: 'Memory + Knowledge Layer', description: 'Docs retrieval, semantic search, RAG pipelines, and indexed repositories.', responsibilities: ['docs retrieval', 'semantic search', 'RAG pipelines', 'indexed repositories'], roles: ['cognition', 'automation'] },
  { id: 'workflow-worker-space', name: 'Workflow Worker Space', shortName: 'Workflow', icon: '🧭', color: '#0f766e', layer: 'Coordination Layer', description: 'DAG execution, task queues, retries, scheduling, and background jobs.', responsibilities: ['DAG execution', 'task queues', 'retries', 'scheduling', 'background jobs'], roles: ['automation', 'execution'] },
  { id: 'eventbus-space', name: 'Eventbus Space', shortName: 'Eventbus', icon: '📡', color: '#06b6d4', layer: 'Coordination Layer', description: 'Redis PubSub, NATS, RabbitMQ, and event streams.', responsibilities: ['Redis PubSub', 'NATS', 'RabbitMQ', 'event streams'], roles: ['automation', 'execution'] },
  { id: 'observability-space', name: 'Observability Space', shortName: 'Obs', icon: '📈', color: '#22c55e', layer: 'Monitoring Layer', description: 'Logs, metrics, tracing, agent monitoring, and runtime analytics.', responsibilities: ['logs', 'metrics', 'tracing', 'agent monitoring', 'runtime analytics'], roles: ['cognition', 'automation'] },
  { id: 'session-runtime-space', name: 'Session Runtime Space', shortName: 'Session', icon: '🧷', color: '#64748b', layer: 'Session Layer', description: 'User sessions, mission isolation, runtime persistence, and checkpointing.', responsibilities: ['user sessions', 'mission isolation', 'runtime persistence', 'checkpointing'], roles: ['automation', 'cognition'] },
  { id: 'model-router-space', name: 'Model Router Space', shortName: 'Router', icon: '🛣️', color: '#eab308', layer: 'Infrastructure Layer', description: 'GPT routing, Claude routing, fallback models, cost optimization, and model selection.', responsibilities: ['GPT routing', 'Claude routing', 'fallback models', 'cost optimization', 'model selection'], roles: ['cognition', 'automation'] },
  { id: 'auth-gateway-space', name: 'Auth Gateway Space', shortName: 'Auth', icon: '🔐', color: '#9333ea', layer: 'Infrastructure Layer', description: 'Auth, API keys, rate limits, and permissions.', responsibilities: ['auth', 'API keys', 'rate limits', 'permissions'], roles: ['automation', 'repair'] },
]

export const SPACE_COLORS = Object.fromEntries(SPACE_CATALOG.map(space => [space.id, space.color])) as Record<string, string>
